version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatgpt
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway
    depends_on:
      - db
    command: migrate
    volumes:
      - ./database/sql:/flyway/sql
      - ./database/conf:/flyway/conf

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatgpt
    depends_on:
      - db
      - flyway
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  db_data:
  node_modules: